### ISSUE TITLE
[speckit.plan] Harden Phase 2

### ISSUE THREAD

**Issue by Boykai** [Boykai/solune#1241]
> **Parent Issue:** #1240 — Harden Phase 2

## 🤖 Agent Task: `speckit.plan`

Create a detailed implementation plan. Break down the specification into actionable steps, identify dependencies, and define the order of execution.

---

## Parent Issue Context

# Harden Phase 2

Solune's reliability, code quality, CI/CD, observability, and developer experience — no new features, just making what exists better.

Phase 2 — Test Coverage Improvement
2.1 Backend: Cover ~30 untested modules (prompt templates, copilot polling internals, MCP tools, chores service, middleware). Raise threshold 75% → 80%.

2.2 Frontend: Cover ~61 untested components (chores: 13, agents: 10, tools: 8, settings: 4, UI: 6, pipeline: 4, chat: 4). Raise thresholds — statements 50%→60%, branches 44%→52%, functions 41%→50%.

2.3 Expand property-based testing — only 4 frontend + 7 backend property test files exist. Add round-trip serialization, API validation edge cases, migration idempotency.

2.4 Integrate @axe-core/playwright into E2E — it's installed but not used in any specs. Add a11y checks to auth, board, chat, settings flows.

---
*Sub-issue created for agent `speckit.plan` — see parent issue #1240 for full context*

**Comment by Boykai** [comment]
**`specs/1240-harden-phase-2/quickstart.md`** (generated by `speckit.plan`)

---

# Quickstart: Harden Phase 2

**Feature**: Test Coverage Improvement
**Date**: 2026-04-10

## Prerequisites

- Python 3.13 with pip
- Node.js 22+ with npm
- Git

## Setup

```bash
# Clone and navigate
git clone https://github.com/Boykai/solune.git
cd solune

# Backend setup
cd solune/backend
python -m venv .venv
source .venv/bin/activate
pip install -e ".[dev]"

# Frontend setup
cd ../frontend
npm install
```

## Running Tests

### Backend

```bash
cd solune/backend

# Run all tests with coverage report
pytest --cov=src --cov-report=term-missing

# Run only property tests
pytest tests/property/ -v

# Run tests for a specific module
pytest tests/unit/test_middleware_request_id.py -v

# Check coverage against current threshold (75%)
pytest --cov=src --cov-fail-under=75
```

### Frontend

```bash
cd solune/frontend

# Run all unit tests with coverage
npx vitest run --coverage

# Run tests for a specific component
npx vitest run src/components/chores/ChoreCard.test.tsx

# Run property tests only
npx vitest run --testPathPattern="property"

# Watch mode for development
npx vitest --watch
```

### E2E Tests

```bash
cd solune/frontend

# Install Playwright browsers (first time only)
npx playwright install

# Run all E2E tests
npx playwright test

# Run a specific E2E spec
npx playwright test e2e/auth.spec.ts

# Run with UI mode for debugging
npx playwright test --ui
```

## Workstream-Specific Guides

### WS 2.1 — Backend Coverage (75% → 80%)

**Find low-coverage files**:

```bash
cd solune/backend
pytest --cov=src --cov-report=term-missing | sort -t% -k4 -n | head -30
```

**Add tests**: Follow existing patterns in `tests/unit/`. Example structure:

```python
# tests/unit/test_middleware_request_id.py
import pytest
from src.middleware.request_id import RequestIdMiddleware

class TestRequestIdMiddleware:
    async def test_adds_request_id_header(self):
        # Test the happy path
        ...

    async def test_preserves_existing_request_id(self):
        # Test edge case
        ...
```

**Bump threshold**: After all tests pass, update `pyproject.toml`:

```toml
[tool.coverage.report]
fail_under = 80
```

### WS 2.2 — Frontend Coverage (statements 50→60%)

**Find untested components**:

```bash
cd solune/frontend
npx vitest run --coverage 2>&1 | grep "0.00" | head -30
```

**Add tests**: Follow existing patterns. Import from `@/test/test-utils`:

```tsx
// src/components/chores/__tests__/ChoreCard.test.tsx
import { render, screen } from '@/test/test-utils';
import { ChoreCard } from '../ChoreCard';

describe('ChoreCard', () => {
  it('renders chore title', () => {
    render(<ChoreCard chore={mockChore} />);
    expect(screen.getByText('Daily standup')).toBeInTheDocument();
  });
});
```

**Bump thresholds**: After all tests pass, update `vitest.config.ts`:

```typescript
thresholds: {
  statements: 60,
  branches: 52,
  functions: 50,
  lines: 60,
},
```

### WS 2.3 — Property-Based Testing

**Backend (Hypothesis)**:

```python
# tests/property/test_api_model_roundtrips.py
from hypothesis import given
from hypothesis import strategies as st
from src.models.some_model import SomeModel

@given(st.builds(SomeModel))
def test_model_roundtrip(model):
    """Model → dict → Model produces identical object."""
    assert SomeModel(**model.model_dump()) == model
```

**Frontend (fast-check)**:

```typescript
// src/lib/apiTypes.property.test.ts
import { test } from '@fast-check/vitest';
import fc from 'fast-check';

test.prop([fc.record({ id: fc.string(), name: fc.string() })])(
  'API type round-trips through JSON',
  ([data]) => {
    expect(JSON.parse(JSON.stringify(data))).toEqual(data);
  },
);
```

### WS 2.4 — Axe-Core E2E Accessibility

**Add a11y test to any E2E spec**:

```typescript
import AxeBuilder from '@axe-core/playwright';

test('should pass accessibility audit', async ({ page }) => {
  await page.goto('/target-route');
  // Wait for content to stabilize
  await page.waitForLoadState('networkidle');

  const results = await new AxeBuilder({ page })
    .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
    .analyze();
  expect(results.violations).toEqual([]);
});
```

## CI Integration

All tests run in GitHub Actions CI:

| Job | Command | Threshold |
|---|---|---|
| Backend | `pytest --cov=src --cov-fail-under=80` | 80% (target) |
| Frontend | `npx vitest run --coverage` | 60/52/50/60 (target) |
| Frontend E2E | `npx playwright test` | All specs pass |
| Backend Advanced | `pytest tests/property/ tests/fuzz/` | All pass (continue-on-error) |

## Validation Checklist

Before submitting a PR for any workstream:

- [ ] All existing tests still pass (`pytest` / `npx vitest run`)
- [ ] New tests pass individually and in full suite
- [ ] Coverage meets or exceeds the target threshold
- [ ] No TypeScript compilation errors (`npx tsc --noEmit`)
- [ ] No Python type errors (`pyright`)
- [ ] E2E tests pass with mocked API (`npx playwright test`)

**Comment by Boykai** [comment]
**`specs/1240-harden-phase-2/research.md`** (generated by `speckit.plan`)

---

# Research: Harden Phase 2

**Feature**: Test Coverage Improvement  
**Date**: 2026-04-10  
**Status**: Complete

## R1: Backend Coverage Gap Analysis

**Decision**: All ~30 previously-untested backend modules now have test files  
**Rationale**: Comprehensive audit of `solune/backend/src/` vs `solune/backend/tests/` confirms
every public module (prompts/, copilot_polling/, mcp_server/tools/, chores/, middleware/) has at
least one corresponding test file. The 75 → 80% threshold increase targets depth of coverage
rather than breadth of new test files.  
**Alternatives considered**: Creating new test files for each module — unnecessary because test
files already exist; the gap is in branch and line coverage within those files.

### Findings

| Module Group | Source Files | Test Files | Notes |
|---|---|---|---|
| prompts/ | 6 | 6 | agent_instructions, issue_generation, label_classification, plan_instructions, task_generation, transcript_analysis |
| copilot_polling/ | 11 | 11 | All internal modules covered including state_validation, recovery, pipeline_state_service |
| mcp_server/tools/ | 8 | 8 | activity, agents, apps, chat, chores, pipelines, projects, tasks |
| services/chores/ | 5 | 5 | chat, counter, scheduler, service, template_builder |
| middleware/ | 5 | 5 | admin_guard, csp, csrf, rate_limit, request_id |

**Action**: Deepen existing test coverage — add edge-case tests, error paths, and branch coverage
to reach 80% threshold. Focus on files with lowest current coverage.

## R2: Frontend Coverage Gap Analysis

**Decision**: ~69 untested components identified across 6 categories  
**Rationale**: Component-level audit of `solune/frontend/src/components/` cross-referenced with
test files (`*.test.tsx`, `*.test.ts`, `__tests__/`) reveals significant gaps in chores (13),
agents (11), tools (9), settings (7), UI (13), and pipeline (16) directories.  
**Alternatives considered**: Only covering high-traffic components — rejected because the
threshold increase from 50%→60% statements requires broad coverage improvement.

### Untested Components by Category

| Category | Count | Components |
|---|---|---|
| chores/ | 13 | AddChoreModal, ChoreCard, ChoreChatFlow, ChoreInlineEditor, ChoreScheduleConfig, ChoresGrid, ChoresPanel, ChoresSaveAllBar, ChoresSpotlight, ChoresToolbar, ConfirmChoreModal, FeaturedRitualsPanel, PipelineSelector |
| agents/ | 11 | AddAgentModal, AgentAvatar, AgentCard, AgentChatFlow, AgentIconCatalog, AgentIconPickerModal, AgentInlineEditor, AgentsPanel, BulkModelUpdateDialog, InstallConfirmDialog, ToolsEditor |
| tools/ | 9 | EditRepoMcpModal, GitHubMcpConfigGenerator, McpPresetsGallery, RepoConfigPanel, ToolCard, ToolChips, ToolSelectorModal, ToolsPanel, UploadMcpModal |
| settings/ | 7 | AIPreferences, PrimarySettings, ProjectSettings, SignalConnection + 3 partially tested |
| ui/ | 13 | alert-dialog, character-counter, confirmation-dialog, copy-button, dialog, hover-card, keyboard-shortcut-modal, popover, skeleton, tooltip + 3 partially tested |
| pipeline/ | 16 | ModelSelector, ParallelStageGroup, PipelineStagesOverview + 13 partially tested |

### Current Thresholds vs Targets

| Metric | Current | Target | Delta |
|---|---|---|---|
| Statements | 50% | 60% | +10% |
| Branches | 44% | 52% | +8% |
| Functions | 41% | 50% | +9% |
| Lines | 50% | 60% | +10% |

## R3: Property-Based Testing Expansion

**Decision**: Expand from 15 files (9 backend + 6 frontend) with new round-trip serialization,
API validation edge cases, and migration idempotency tests  
**Rationale**: Property-based testing with Hypothesis (backend) and fast-check (frontend) is
already established with proper CI/dev profiles. Expanding coverage to serialization boundaries
and validation edge cases catches bugs that example-based tests miss.  
**Alternatives considered**: Fuzz testing expansion — already 4 fuzz files in backend; property
tests are more structured and provide better regression guarantees.

### Existing Property Tests

**Backend (Hypothesis 6.131.0+)**:

| File | Strategy | Type |
|---|---|---|
| test_pipeline_state_machine.py | RuleBasedStateMachine | Stateful |
| test_markdown_parser_roundtrips.py | text strategies | Round-trip |
| test_pipeline_states.py | composite strategies | Invariant |
| test_model_validation.py | builds strategies | Validation |
| test_bounded_cache_stateful.py | RuleBasedStateMachine | Stateful |
| test_blocking_queue.py | integers + lists | Concurrency |
| test_model_roundtrips.py | builds strategies | Round-trip |

**Frontend (fast-check/vitest 0.4.0)**:

| File | Strategy | Type |
|---|---|---|
| formatTime.property.test.ts | arbitrary timestamps | Round-trip |
| utils.property.test.ts | string strategies | Invariant |
| time-utils.property.test.ts | date strategies | Invariant |
| case-utils.property.test.ts | string strategies | Round-trip |
| pipelineMigration.property.test.ts | pipeline configs | Idempotency |
| buildGitHubMcpConfig.property.test.ts | config objects | Invariant |

### Expansion Targets

- **Round-trip serialization**: Model → JSON → Model for all API request/response types
- **API validation edge cases**: Boundary values, Unicode, empty strings, max-length fields
- **Migration idempotency**: Pipeline migrations applied twice produce same result

## R4: Axe-Core Playwright Integration

**Decision**: Extend @axe-core/playwright usage from 2 files to 6 files (auth, board, chat,
settings flows)  
**Rationale**: @axe-core/playwright 4.10.1 is installed and working in `ui.spec.ts` and
`protected-routes.spec.ts`. The pattern uses `new AxeBuilder({ page }).analyze()` with WCAG 2.1
tags. Auth, board, chat, and settings flows are user-critical paths missing a11y checks.  
**Alternatives considered**: jest-axe for unit tests — already installed (jest-axe 10.0.0) but
E2E-level a11y catches rendering and interaction issues that unit tests miss.

### Current State

| File | Has AxeBuilder | A11y Tests |
|---|---|---|
| ui.spec.ts | ✓ | 1 test (login page audit) |
| protected-routes.spec.ts | ✓ | 1 test per route (redirect + a11y) |
| auth.spec.ts | ✗ | None |
| board-navigation.spec.ts | ✗ | None |
| chat-interaction.spec.ts | ✗ | None |
| settings-flow.spec.ts | ✗ | None |

### Integration Pattern

```typescript
import AxeBuilder from '@axe-core/playwright';

// After page loads and stabilizes:
const results = await new AxeBuilder({ page })
  .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])
  .analyze();
expect(results.violations).toEqual([]);
```

### E2E Fixture Architecture

- `fixtures.ts`: Unauthenticated, mocks `/api/**` with 401 for auth/me
- `authenticated-fixtures.ts`: Authenticated, provides `mockApi` helper
- Auth/UI specs use `fixtures.ts`; board/chat/settings use `authenticated-fixtures.ts`

## R5: Test Infrastructure and CI

**Decision**: Leverage existing CI pipeline (9 jobs) without structural changes  
**Rationale**: CI already runs Backend, Frontend, Frontend E2E as separate jobs. Coverage
thresholds are enforced in pyproject.toml (backend) and vitest.config.ts (frontend). Threshold
bumps require only config changes.  
**Alternatives considered**: Adding dedicated coverage jobs — unnecessary overhead; existing jobs
already collect and enforce coverage.

### CI Job Structure

| Job | Blocking | Runs |
|---|---|---|
| Backend | Yes | pytest with coverage |
| Backend Advanced Tests | No (continue-on-error) | Property/chaos/fuzz tests |
| Frontend | Yes | vitest with coverage |
| Frontend E2E | No (continue-on-error) | Playwright specs |
| Docs Lint | Yes | markdownlint |
| Diagrams | Yes | Diagram validation |
| Contract Validation | Yes | API contract checks |
| Build Validation | Yes | Full build check |
| Docker Build | Yes (needs backend+frontend) | Docker image build |

### Test Configuration Summary

**Backend (pyproject.toml)**:
- `fail_under = 75` (target: 80)
- `asyncio_mode = "auto"`
- `branch = true` (branch coverage enabled)
- Mutation testing: mutmut 3.2.0 for api/, middleware/, utils.py

**Frontend (vitest.config.ts)**:
- Provider: v8
- Environment: happy-dom
- Globals: true
- Coverage: all source files included
